### ISSUE TITLE
Method refund is deprecated

### ISSUE THREAD

**Issue by 0xbaadf00d** [payzen/payzen-webservices-v5-sdk-java#18]
Hi,

What is the alternative to the deprecated method _refund_ ?

```
[warn] /projekt/app/actors/SyncPayoutRequestActor.java:234: refund(java.lang.String,com.lyra.vads.ws.v5.PaymentRequest,java.util.Map<java.lang.String,java.lang.String>...) in eu.payzen.webservices.sdk.Payment has been deprecated
```

Sincerely

**Comment by profesorfalken** [comment]
Hello, 

As you can see in the code comments: https://github.com/payzen/payzen-webservices-v5-sdk-java/blob/master/src/main/java/eu/payzen/webservices/sdk/Payment.java

That method have been added to the API without following as example the structure of the basic methods (create, update, cancel, etc) originally available in this SDK. The method API should provide either a reduced and simple number of parameters or a builder patter allowing to create a fluent call. In that case the method exposes directly the WebService objects.

This SDK is just used for an example of WebServices use and it was provided to the community as it is. It can be forked and improved/modified in order to fulfill different needs. 
Anyone can provide a pull request that will be accepted if valid. So feel free to propose a right implementation of refund method respecting the simple/builder pattern.

Best regards

**Comment by profesorfalken** [comment]
There is a working refund method in current version, so I close this outdated issue.
